### ISSUE TITLE
DoBlastzChainNet.pl

### ISSUE THREAD

**Issue by ErinZhang1998** [hillerlab/Parasol_LSF_Slurm#1]
Hi! 

Thanks for creating this Parasol wrapper for Slurm.

If we want to do something as indicated by this tutorial posted on genomewiki,
http://genomewiki.ucsc.edu/index.php/DoBlastzChainNet.pl

`/data/scripts/doBlastzChainNet.pl  DEF -verbose=2 -noDbNameCheck \
 -workhorse=localhost -bigClusterHub=localhost -skipDownload \
   -dbHost=localhost -smallClusterHub=localhost \
     -trackHub -fileServer=localhost -syntenicNet`

Specifically, if we want to run something that hands originally to Parasol, what should we do?

I have read the README.html but still felt quite confused.

Please help!!

**Comment by MichaelHiller** [comment]
Hi Erin, 

this should work. Please test if the parasol wrapper works on your system (para make, that it pushes crashed jobs again, para time, etc)  using the DieRandom.perl script. 

If that works, just replace the para make jobList calls in doBlastzChainNet.pl with the parasol for slurm wrapper. The syntax is the same, except that you have to specify a jobListName (e.g. blastz for the blastz runs). 

Please see the README.html for more details. 

- Michael

**Comment by ErinZhang1998** [comment]
but if para.pl is not even a command yet, how would you make and push and ect.?

what would you need to do to the paraSlurm.perl?

Sorry I am not sure if I understand what to install before I could do para.pl make

**Comment by MichaelHiller** [comment]
paraSlurm.perl is mostly equivalent to Jim Kent's para. Since it is a perl script, you don't have to compile anything. Just copy it to your bin dir and add this dir to $PATH. 
You should be able to replace the 
para make jobList
with something like 
paraSlurm.perl make lastzJobs jobList

**Comment by ErinZhang1998** [comment]
I see! 

but it does not seem to work on the example (DieRandomTime)

`**** PUSH Jobs to queue: short
**** Number of cores requested: 1
**** MB of memory requested: 10000
Waiting to get ./lockFile.jobListTest   ..... [Takes too long? Did a previous para run died? If so, open a new terminal and   rm -f ./lockFile.jobListTest ] .....  got it
sbatch: error: Batch job submission failed: No partition specified or system default partition
######### ERROR ######### in pushSingleJob: sbatch <<< "$( printf '#!/bin/bash
#SBATCH -J jobListTest
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=10000
#SBATCH --time=01:00:00
#SBATCH -o ./.para/jobListTest/1/o.0
#SBATCH -e ./.para/jobListTest/1/o.0
DieRandomTime.perl 30 -T 0.5 > resultsDir/run0.txt' )" failed with exit code 256`

I suppose it was meant to be an example?

Could you explain a bit further about setting up the parameters?
```
# PARAMETERS YOU MUST CONFIGURE
my $clusterHeadNode = "lanec1.compbio.cs.cmu.edu";		# specify here the hostname of the cluster head node (the computer that is able to submit jobs to LSF). The script will only run when executed on this node. 
my $queue = "short";						# short queue is the default
my $maxRunTimeQueue = "long";			# the queue with the maximum runtime
# used if jobs reach the run time limit of a queue and have to be resubmitted (used in pushCrashed)
my %Queue2Order;
$Queue2Order{"short"}  = 0;
$Queue2Order{"shortmed"}  = 1;
$Queue2Order{"medium"} = 2;
$Queue2Order{"day"}    = 3;
$Queue2Order{"long"}   = 4;
my %Order2Queue;
$Order2Queue{0} = "short";
$Order2Queue{1} = "shortmed";
$Order2Queue{2} = "medium";
$Order2Queue{3} = "day";
$Order2Queue{4} = "long";
```

especially the 2 parameters 

```
my $queue = "short";						# short queue is the default
my $maxRunTimeQueue = "long";
```


that is specific to each cluster right?

**Comment by MichaelHiller** [comment]
Your slurm cluster settings differ from ours. Looks like you have to specify the ' -p PARTITION' parameter to tell slurm which partition to use. You can do that pass on any parameter to sbatch with paraSlurm.perl's parameter -p  (e.g. paraSlurm.perl ... -p "-p PARTITION"). 

The queue's are just logical names that are translated just into max run times 
    # add runtime, depending on the queue
    if ($queue eq "short") {
        $jobFileFixedPart .= "#SBATCH --time=01:00:00\n";
    }elsif ($queue eq "shortmed") {
        $jobFileFixedPart .= "#SBATCH --time=03:00:00\n";
    }elsif ($queue eq "medium") {
        $jobFileFixedPart .= "#SBATCH --time=08:00:00\n";
    }elsif ($queue eq "day") {
        $jobFileFixedPart .= "#SBATCH --time=24:00:00\n";
    }elsif ($queue eq "long") {
        # 2 weeks
        $jobFileFixedPart .= "#SBATCH --time=336:00:00\n";
        $jobFileFixedPart .= "#SBATCH --partition=long\n";
    }else {
        die "ERROR: queue is neither short/shortmed/medium/day/long.\n";
    }
which you can change in the code.

**Comment by ErinZhang1998** [comment]
thanks a lot!!!

yeah I added 

`perl paraSlurm.perl push jobListTest jobList -q short -p "--partition=short1 -W 0:50"`

but it still says that 

`sbatch: error: Batch job submission failed: No partition specified or system default partition`

I suppose that the "-p" for paraSlurm.perl is as specified in README.html: it is to specify other parameters needed for "bsub"

hmmm

>.<


Follow-up on the parameter question

looking at the line

`$jobFileFixedPart .= "#SBATCH --partition=long\n";`

"long" looks like a name of a partition?

**Comment by MichaelHiller** [comment]
I haven't seen this error message before. Pls contact your sys admin and try to get the sbatch command working from the command line. This will tell you which parameters you need to specifically pass on to paraSlurm.perl

You can run the perl script with -v to see what the submitted sbatch command is. 

--partition=long would only be added to the sbatch command if you specify -q long

**Comment by ErinZhang1998** [comment]
Hi Michael

I think the problem is that even though I specify -p "-p pfen2" 
where pfen2 is the name of a partition

in the actual sbatch script that is send, the critical line
"#SBATCH -p pfen2"
is not there

so I hard-coded in pushSingleJob
along with 
	$jobPrefix .= "#SBATCH -p pfen2\n";
	$jobPrefix .= "#SBATCH -o $outFile\n";
	$jobPrefix .= "#SBATCH -e $outFile\n";

and that worked


any idea why the parameter didn't carry over to the actual sbatch script

**Comment by ErinZhang1998** [comment]
(ignore my typo...bad at spelling)

**Comment by MichaelHiller** [comment]
You are right. That was a bug. I have tried to fix it now. 
Could you pls test if "-p pfen2" is now automatically added if you specify the -p parameter?

**Comment by ErinZhang1998** [comment]
yeah, but the new problem is that somehow running paraSlurm.perl clean cause a problem related to sacct 

I think I mention in another post that there is no option --delimiter in our Slurm for some reason.

hmmmm....

I can try push with a new jobTestList but I can't clean any so I don't want to create too many of them with each command

**Comment by MichaelHiller** [comment]
If your slurm version does not support the --delimiter option, then please adapt the code in the function that runs sacct (runSingleJob_sacct and runsacct) and parses the output. I have set delimiter to tab because that is easy to parse. I would assume you will have to change the lines
  split(/\t/, $line
to whatever your delimiter is.

**Comment by ErinZhang1998** [comment]
yeah, I think if you use the option -p the delimiter is \|
so I split with \| and it works!

Thanks!

**Comment by ErinZhang1998** [comment]
also sorry that I forgot to mention the -p problem  is solved

but running 
`perl paraSlurm.perl make jobListTest jobList -q short -p "-p pool1 -t 0:50"`

it would say:

```
**** PUSH Jobs to queue: short
**** Number of cores requested: 1
**** MB of memory requested: 10000
Waiting to get ./lockFile.jobListTest   ..... [Takes too long? Did a previous para run died? If so, open a new terminal and   rm -f ./lockFile.jobListTest ] .....  got it
DONE.
1 jobs pushed using parameters: -q short -p pool1 -t 0:50

Waiting to get ./lockFile.jobListTest   ..... [Takes too long? Did a previous para run died? If so, open a new terminal and   rm -f ./lockFile.jobListTest ] .....  got it
WAIT UNTIL jobList is finished .....
Waiting to get ./lockFile.jobListTest   ..... [Takes too long? Did a previous para run died? If so, open a new terminal and   rm -f ./lockFile.jobListTest ] .....  got it
numJobs: 1      	RUN: 0      	PEND: 0      	DONE: 0      	FAILED: 1        (0 of them failed 3 times)	allDone: NO
Waiting to get ./lockFile.jobListTest   ..... [Takes too long? Did a previous para run died? If so, open a new terminal and   rm -f ./lockFile.jobListTest ] .....  got it
sbatch: error: Batch job submission failed: No partition specified or system default partition
######### ERROR ######### in pushSingleJob: sbatch <<< "$( printf '#!/bin/bash
#SBATCH --time=01:00:00
#SBATCH -o ./.para/jobListTest/1/o.0
#SBATCH -e ./.para/jobListTest/1/o.0
HelloWorld.perl > resultsDir/hello.txt' )" failed with exit code 256
```

note the "No partition specified or system default partition"
I am not sure if this stems from a similar problem for make

**Comment by ErinZhang1998** [comment]
Hi Michael

now that the basic commands are kind of working, even though jobs all crash....

I am looking over the doBlastChainNet.pl file again

It seems like doBlastzChainNet.pl makes a lot of call to components of the parasol architecture (not sure if this is the right way to express it)
but an example would be:
`$paraHub`, which is  the job scheduler. 

>The Parasol system consists primarily of the scheduling server paraHub and two clients, parasol and para

I am a bit confused about where para.pl comes in.
It seems to me that paraSlurm.perl covers basically the function of "para"?

Please correct me if I am wrong

**Comment by jakevc** [comment]
@ErinZhang1998 were you able to successfully adapt DoBlastzChainNet.pl to SLURM? I also would like to run it on SLURM, and have been evaluating my options. This looks promising.

**Comment by hasibaasma** [comment]
Hi @ErinZhang1998 and @jakevc 
Did you guys worked it out for SLURM?

**Comment by jakevc** [comment]
@hasibaasma, I actually ended up running it locally using a collection of Rscripts from the package CNEr, here is the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/CNEr/inst/doc/PairwiseWholeGenomeAlignment.html) describing how to use the package for pairwise whole genome alignment.
