### ISSUE TITLE
what if the example in README.html fails?

### ISSUE THREAD

**Issue by ErinZhang1998** [hillerlab/Parasol_LSF_Slurm#4]
Hi Michael

So now that we are running doBlastzChainNet.pl, I realize that some of the problems that I have seen might be relevant (which I kind of ignored before), one of them being that the example jobList 

```
DieRandomTime.perl 30 -T 0.5 > resultsDir/run0.txt
DieRandomTime.perl 33 -T 0.5 > resultsDir/run1.txt
DieRandomTime.perl 38 -T 0.5 > resultsDir/run2.txt
DieRandomTime.perl 40 -T 0.5 > resultsDir/run3.txt
DieRandomTime.perl 49 -T 0.5 > resultsDir/run4.txt
```

Even though paraSlurm.pl seemed to have pushed everything
as 
`DONE. 5 jobs pushed using parameters: -q short -t 0:50` indicates, 

but

`numJobs: 5      	RUN: 0      	PEND: 0      	DONE: 0      	FAILED: 5        (0 of them failed 3 times)	allDone: NO`

all the jobs failed

and 

```
mv: cannot stat `./.para/jobListTest/1/o.1': No such file or directory
mv: cannot stat `./.para/jobListTest/1/o.2': No such file or directory
mv: cannot stat `./.para/jobListTest/1/o.3': No such file or directory
```

do you have any idea of why all the jobs are failling?

Thanks!! :)

Erin

**Comment by MichaelHiller** [comment]
with -T 0.5, jobs should fail 50% of the time. 
But paraSlurm should resubmit them. Up to 3 times. 
I don't know why ./.para/jobListTest/1/o.1 does not exist. This should be the file where Slurm writes any output to.
